### ISSUE TITLE
Auto-filling of recipe through JEI inconsistent

### ISSUE THREAD

**Issue by UnlimitedHugs** [zerofall/EZStorage#24] opened 2016-03-22 10:56 UTC
When filling a crafting recipe through JEI, sometimes not all items in the recipe are added to the crafting grid, despite them being available. Seems to happen when selecting several recipes in a row.
Reopening the interface fixes this.

**Comment by zerofall** [comment] 2016-03-29 17:39
Duplicate of #14

**Closed as completed by zerofall** 2016-03-29 17:39 UTC
Labels: duplicate
